# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    php_errors:
        log: true
    session:
        sid_length:             64
        sid_bits_per_character: 4
